project:
  type: website
  render:
    - "*.qmd"
    - "!slides/"
  resources: 
    - "slides/*.html"
    - "slides/*.pdf"
    - "slides/img/"
    - "slides/libs/"
    - "slides/css/"
    - "slides/*_files/"
  preview: 
    port: 4444

website:
  title: "PhD websites"

  repo-url: "https://github.com/andrewheiss/2026-02-06_ays-dissertation-colloquium"
  repo-actions: [source, issue]

  navbar:
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - href: quarto.qmd
        text: How to make a Quarto website
    right:
      - icon: github
        href: "https://github.com/andrewheiss/2026-02-06_ays-dissertation-colloquium"


author:
- name: Andrew Heiss
  url: "https://www.andrewheiss.com"
  affiliation: Georgia State University
  email: aheiss@gsu.edu
  orcid: 0000-0002-3948-3914

format:
  html:
    theme:
      - zephyr
      - brand
    toc: true
