---
title: "How to make a Quarto website"
date: 2026-02-06
---

## Sample

<a class="btn btn-success btn-lg" target="_blank" href="files/example-site-skeleton.zip">{{< fa file-zipper >}} &ensp;Download an example site skeleton</a>

## Getting started

::: {.callout-tip}
### Resources!

- [Quarto documentation](https://quarto.org/)
- [Workshop materials](https://andrewheiss.github.io/quarto-websites_2025-10/)
:::

Choose one editor and follow the steps:

::: {.panel-tabset}

### RStudio

- Download and install RStudio: <https://posit.co/downloads/>
  - Make sure RStudio is version 2022.07+.
- Quarto comes pre-installed.
  - Make sure Quarto is version 1.8+.

### Positron

- Download and install Positron: <https://positron.posit.co/download.html>
- Quarto comes pre-installed.
  - Make sure Quarto is version 1.8+.

### VS Code

- Download and install VS Code: <https://code.visualstudio.com/download/>
- Download and install Quarto: <https://quarto.org/docs/get-started/>
- Install the following extensions:
  - Quarto Extension: <https://marketplace.visualstudio.com/items?itemName=quarto.quarto/>
  - Jupyter Extension: <https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter/> 
:::

## Working with Quarto Markdown

::: {.callout-tip}
### Resources!

- [Markdown basics](https://quarto.org/docs/authoring/markdown-basics.html)
- [Figures](https://quarto.org/docs/authoring/figures.html)
- [Tables](https://quarto.org/docs/authoring/tables.html)
- [Article layout](https://quarto.org/docs/authoring/article-layout.html)
- [Citations](https://quarto.org/docs/authoring/citations.html)
- [Workshop materials](https://andrewheiss.github.io/quarto-websites_2025-10/materials/01-intro/)
:::

**You can use Quarto even if you never use any computational output!** It's fantastic for generating websites from Markdown, even if you don't use R/Python/Stata/whatever.

Quarto supports [R](https://quarto.org/docs/computations/r.html), [Python](https://quarto.org/docs/computations/python.html), [Observable JS](https://quarto.org/docs/computations/ojs.html), and [Julia](https://quarto.org/docs/computations/julia.html) natively. You can even make it support things like [Stan](https://forum.posit.co/t/add-stan-models-to-markdown-quarto-documents-with-syntax-formatting-and-use-them-in-r-chunks/164309) or Stata ([through R](https://drexelccuh.quarto.pub/rendering-a-reproducible-report-with-stata-and-quarto/) or [through Python](https://friosavila.github.io/stata_do/stata_do1.html)).

## Configuring Quarto websites

::: {.callout-tip}
### Resources!

- [Quarto documentation for creating a website](https://quarto.org/docs/websites/)
- [Website navigation](https://quarto.org/docs/websites/website-navigation.html)
- [About pages](https://quarto.org/docs/websites/website-about.html)
- [Creating a blog](https://quarto.org/docs/websites/website-blog.html)
- [Workshop materials for creating basic websites](https://andrewheiss.github.io/quarto-websites_2025-10/materials/basic-websites/)
- [Workshop materials for advanced website features](https://andrewheiss.github.io/quarto-websites_2025-10/materials/advanced-websites/)
:::

## Publishing Quarto websites

::: {.callout-tip}
### Resources!

- [Quarto documentation on publishing](https://quarto.org/docs/publishing/)
- [Workshop slides on publishing](https://andrewheiss.github.io/quarto-websites_2025-10/materials/publishing/)
:::

Easy:

- **Quarto Pub**: Free!; everything's public; no custom domains
- **Posit Connect Cloud**: Free!; everything's public; no custom domains
- **Posit Connect**: \$\$; public and private; custom domains

Medium:

- **GitHub Pages**: Free!; everything's public; custom domains
- **Netlify**: Free and paid; public and private; custom domains

Advanced:

- **DIY**: Set up a server yourself and do whatever you want

What I use:

- **Quarto Pub**: [example](https://andrewheiss.quarto.pub/random-effects-and-marginaleffects/) + [example](https://andrewheiss.quarto.pub/arnova-2025-proposal/)
- **GitHub Pages**: [example](https://profmusgrave.github.io/qatarcars/) + [example](https://foreignassistance.andrewheiss.com/) + [example](https://nullworlds.andrewheiss.com/)
- **DIY**: [example](https://www.andrewheiss.com/) + [example](https://stats.andrewheiss.com/silent-skywalk/)
